//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectHolder
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ProjectDescription { get; set; }
        public string Screenshot { get; set; }
        public string LinkToRepository { get; set; }
        public string LanguagesUsed { get; set; }
    }
}
